/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.queue-consumer-ts.jsonc --include-runtime=false` (hash: 30ff076630d0979938934b1566d2dd90)
interface __BaseEnv_Env {
	DB: D1Database;
	LINEAR_API_URL: "https://api.linear.app/graphql";
	LINEAR_HUMAN_APPROVAL_STATE_ID: "71738607-03fd-49f2-b4be-b2aac29ccd13";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/queue-consumer");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LINEAR_API_URL" | "LINEAR_HUMAN_APPROVAL_STATE_ID">> {}
}
