/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.queue-consumer-ts.jsonc --include-runtime=false` (hash: 9b62d2734d27ffabc75be34f4fb1bf63)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	LINEAR_API_URL: "https://api.linear.app/graphql";
	LINEAR_HUMAN_APPROVAL_STATE_ID: "71738607-03fd-49f2-b4be-b2aac29ccd13";
	LINEAR_PROJECT_ID: "99426d9b-cda7-4db4-9136-692a95a0b090";
	LINEAR_START_STATE_NAME: "Todo";
	LINEAR_APPROVAL_STATE_NAMES: "In Progress";
	LINEAR_REJECTION_STATE_NAMES: "Canceled";
	LINEAR_APP_ACTOR_ID: "f010429f-7734-4f3f-9b4b-13a4abb9b4ab";
	LINEAR_TEAM_ID: "ac53207d-68c0-42f1-a245-c1baf047f234";
	GITHUB_API_URL: "https://api.github.com";
	TRIAL_REPOSITORY: "sachinkundu/deos";
	TRIAL_DISPATCH_ENABLED: "false";
	CODEX_AUTH_PROFILE_ID: "controlled-trial";
	CAPABILITY_BASE_URL: "https://deos-queue-consumer-ts.skundu.workers.dev/capabilities";
	LINEAR_APP_ACCESS_TOKEN: string;
	GITHUB_APP_ID: string;
	GITHUB_APP_PRIVATE_KEY: string;
	GITHUB_INSTALLATION_ID: string;
	CODEX_AUTH_ENCRYPTION_KEY: string;
	CAPABILITY_SIGNING_SECRET: string;
	CLEANUP_AUDIT_SECRET: string;
	Sandbox: DurableObjectNamespace<import("./src/queue-consumer").Sandbox>;
	ORCHESTRATION_WORKFLOW: Workflow<Parameters<import("./src/queue-consumer").DeosWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/queue-consumer");
		durableNamespaces: "Sandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LINEAR_API_URL" | "LINEAR_HUMAN_APPROVAL_STATE_ID" | "LINEAR_PROJECT_ID" | "LINEAR_START_STATE_NAME" | "LINEAR_APPROVAL_STATE_NAMES" | "LINEAR_REJECTION_STATE_NAMES" | "LINEAR_APP_ACTOR_ID" | "LINEAR_TEAM_ID" | "GITHUB_API_URL" | "TRIAL_REPOSITORY" | "TRIAL_DISPATCH_ENABLED" | "CODEX_AUTH_PROFILE_ID" | "CAPABILITY_BASE_URL" | "LINEAR_APP_ACCESS_TOKEN" | "GITHUB_APP_ID" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_INSTALLATION_ID" | "CODEX_AUTH_ENCRYPTION_KEY" | "CAPABILITY_SIGNING_SECRET" | "CLEANUP_AUDIT_SECRET">> {}
}
declare module "*.yaml" {
	const value: string;
	export default value;
}
declare module "*.md" {
	const value: string;
	export default value;
}