/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 5f556ca752ffc3531f0278d787cbea9b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "deos-voxdez.cloudflareaccess.com";
	ACCESS_AUD: "c12828abda88ac73e394039f6e0b87a9bc5f2d78922463c37a72ccca55bedec7";
	ALLOWED_EMAIL: "sachinkundu@gmail.com";
	GITHUB_CLIENT_ID: "Iv23likxukpheraNrZlx";
	GITHUB_SESSIONS: DurableObjectNamespace<import("./worker/index").GitHubSession>;
	DEOS_PORTAL: Fetcher /* deos-workflow-portal */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "GitHubSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_EMAIL" | "GITHUB_CLIENT_ID">> {}
}
