/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=portal/bettaview/wrangler.jsonc --include-runtime=false portal/bettaview/worker-configuration.d.ts` (hash: 113fcc4a5888a61b1ab394f429e0041a)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "deos-voxdez.cloudflareaccess.com";
	ACCESS_AUD: "c12828abda88ac73e394039f6e0b87a9bc5f2d78922463c37a72ccca55bedec7";
	ALLOWED_EMAIL: "sachinkundu@gmail.com";
	GITHUB_CLIENT_ID: "Iv23likxukpheraNrZlx";
	GITHUB_CLIENT_SECRET: string;
	REVIEW_CONTINUATION_SECRET: string;
	GITHUB_SESSIONS: DurableObjectNamespace<import("./worker/index").GitHubSession>;
	DEOS_REVIEW_CONTINUATION: Service /* entrypoint ReviewContinuation from deos-queue-consumer-ts */;
	DEOS_PORTAL: Fetcher /* deos-workflow-portal */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "GitHubSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_EMAIL" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "REVIEW_CONTINUATION_SECRET">> {}
}
