/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=portal/wrangler.jsonc --include-runtime=false portal/src/worker-configuration.d.ts` (hash: 1d59312c384d525ed9dfdb0e607fc0b8)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "deos-voxdez.cloudflareaccess.com";
	ACCESS_AUD: "c12828abda88ac73e394039f6e0b87a9bc5f2d78922463c37a72ccca55bedec7";
	ALLOWED_EMAIL: "sachinkundu@gmail.com";
	PROJECT_ID: "99426d9b-cda7-4db4-9136-692a95a0b090";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_EMAIL" | "PROJECT_ID">> {}
}
