/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=portal/wrangler.jsonc --include-runtime=false portal/src/worker-configuration.d.ts` (hash: 4e0ee9ea73064ee35a5cef24cd9a6ba5)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "deos-voxdez.cloudflareaccess.com";
	ACCESS_AUD: "c12828abda88ac73e394039f6e0b87a9bc5f2d78922463c37a72ccca55bedec7";
	ALLOWED_EMAIL: "sachinkundu@gmail.com";
	OPENROUTER_SUPPORTED_MODELS: "deepseek/deepseek-v4-pro";
	ROUTE_ADMIN: Service /* entrypoint RouteAdmin from deos-queue-consumer-ts */;
	RETRY_ADMIN: Fetcher /* deos-queue-consumer-ts */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_EMAIL" | "OPENROUTER_SUPPORTED_MODELS">> {}
}
