/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 371272baf6b5b4b0483cea14a6484901)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "deos-voxdez.cloudflareaccess.com";
	ACCESS_AUD: "c12828abda88ac73e394039f6e0b87a9bc5f2d78922463c37a72ccca55bedec7";
	ALLOWED_EMAIL: "sachinkundu@gmail.com";
	PROJECT_ID: "99426d9b-cda7-4db4-9136-692a95a0b090";
	OPENROUTER_SUPPORTED_MODELS: "anthropic/claude-sonnet-4.5";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ALLOWED_EMAIL" | "PROJECT_ID" | "OPENROUTER_SUPPORTED_MODELS">> {}
}
